EDU_ONLINE/urls.py
from django.conf.urls import url,include
# from django.contrib import admin
import xadmin

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^user/', include("users.urls", namespace='user')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^org/', include("organization.urls", namespace='org')),
]

apps/organization/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'amy'
__date__ = '18-7-11 下午4:38'
from django.conf.urls import url
from django.views.static import serve
from EDU_ONLINE.settings import MEDIA_URL
from .views import CourseList, TeacherList, OrgList, AddUserAsk, OrgDetailList, OrgCourseList

urlpatterns = [
    url(r'course_list/$', CourseList.as_view(), name='courseList'),
    url(r'teacher_list/$', TeacherList.as_view(), name='teacherList'),
    url(r'org_list/$', OrgList.as_view(), name='orgList'),
    url(r'add_ask/$', AddUserAsk.as_view(), name='addAsk'),

    url(r'org_detail/(\d+)', OrgDetailList.as_view(), name='org_detail'),
    url(r'course_detail/(\d+)', OrgCourseList.as_view(), name='course_detail'),

    # 用于处理media文件下的图片
    url(r'media/(?P<path>.*)', serve, {'document_root': MEDIA_URL})
]

apps/users/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'amy'
__date__ = '18-6-8 上午10:21'
from django.conf.urls import url
from .views import index, LoginView, RegisterView, ActiveEmailView, reActiveEmail, ForgetPassword, ResetPassword

urlpatterns = [
    url(r'index/$', index, name='index'),
    url(r'login/$', LoginView.as_view(), name='login'),
    url(r'register/$', RegisterView.as_view(), name='register'),
    url(r'user/active/(?P<code>.*)/$', ActiveEmailView.as_view(), name='active'),
    url(r'resend_email/$', reActiveEmail, name='reactive'),
    url(r'forget/$', ForgetPassword.as_view(), name='forget_pwd'),
    # url(r'^forget/$', find_page),
    url(r'reset_password/$', ResetPassword.as_view(), name='reset'),
    # url(r'^my_mail/$', myMail)
]

apps/users/forms.py
# _*_ coding: utf-8 _*_
__author__ = 'amy'
__date__ = '18-6-8 下午3:04'
from django import forms
from captcha.fields import CaptchaField


class LoginForm(forms.Form):
    username = forms.CharField(required=True, min_length=5)
    password = forms.CharField(required=True)


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True,min_length=5)
    captcha = CaptchaField(error_messages={'invalid': '验证码错误'})


class ForgetForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={'invalid': '验证码错误'})


class FindPasswordForm(forms.Form):
    password = forms.CharField(required=True, min_length=6,max_length=20)
    password2 = forms.CharField(required=True, min_length=6,max_length=20)

templates/change_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改成功</title>
    <style>
{#        .one{#}
{#            height:200px;#}
{#            width: 500px;#}
{#            margin-top: 50%;#}
{#            margin-left: 50%;#}
{#            color: #2b333b;#}
{#            text-align: center;#}
{#        }#}
{#        .two{#}
{#            text-decoration: none;#}
{#        }#}
    </style>
</head>
<body>
    <div class="one">
        <p>您的密码已修改成功，<a href="/login/" class="two">点击重新登录</a></p>
    </div>
</body>
</html>

templates/course-list.html
{% extends 'base.html' %}
{% block title %}慕学在线网 - 公开课列表{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
{% endblock %}

templates/forgetpwd.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>慕学网首页</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/login.css">
</head>
<body>
<!--提示弹出框-->
<div class="successbox dialogbox" id="jsSuccessTips">
    <h1>成功提交</h1>
    <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
    <div class="cont">
        <h2>您的需求提交成功！</h2>
        <p></p>
    </div>
</div>
<div class="resetpassbox dialogbox" id="jsSetNewPwd">
    <h1>重新设置密码</h1>
    <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
    <p class="green">请输入新密码</p>
    <form id="jsSetNewPwdForm">
        <div class="box">
            <span class="word2">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</span>
            <input type="password" name="password" id="jsResetPwd" placeholder="请输入新密码"/>
        </div>
        <div class="box">
            <span class="word2">确&nbsp;认&nbsp;密&nbsp;码</span>
            <input type="password" name="password2" id="jsResetPwd2" placeholder="请再次输入新密码"/>
        </div>
        <div class="box">
            <span class="word2">验&nbsp;&nbsp;证&nbsp;&nbsp;码</span>
{#            {{ forgetForm.captcha }}#}
            <input type="text" name="code" id="jsResetCode" placeholder="请输入手机验证码" />
        </div>
        <div class="error btns" id="jsSetNewPwdTips"></div>
        <div class="button">
            <input type="hidden" name="mobile" id="jsInpResetMobil" />
            <input id="jsSetNewPwdBtn" type="button" value="提交" />
        </div>
        <input type='hidden' name='csrfmiddlewaretoken' value='mymQDzHWl2REXIfPMg2mJaLqDfaS1sD5' />
    </form>
</div>
<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">慕学网，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>33333333</span></li>
                <li><a href="login.html">[登录]</a></li>
                <li class="active"><a href="/forgetpwd/">[忘记密码]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="index.html"></a>
                <h1>忘记密码</h1>
                <a class="index-font" href="index.html">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                        <li><a href=""><img width="483" height="472" src="/static/images/57a801860001c34b12000460.jpg" /></a></li>
                        <li><a href=""><img width="483" height="472" src="/static/images/57a801860001c34b12000460.jpg" /></a></li>
                        <li><a href=""><img width="483" height="472" src="/static/images/57a801860001c34b12000460.jpg" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>忘记密码</h2>
                <form id="jsFindPwdForm" method="post" action="{% url 'user:forget_pwd' %}" autocomplete="off">

                    <div class="form-group marb20 {% if forgetForm.errors.email %}errorput{% endif %}">
                        <label>帐&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号</label>
                        <input type="text" id="account" name="email" value="None" placeholder="邮箱" />
                    </div>
                    <div class="form-group captcha1 marb38 {% if forgetForm.errors.captcha %}errorput{% endif %}">
                        <label>验&nbsp;证&nbsp;码</label>
                        {{ forgetForm.captcha }}
{#                        <img src="/captcha/image/997454dc58799e806f18d21eac296581a8c6ef02/" alt="captcha" class="captcha" /> <input id="id_captcha_0" name="captcha_0" type="hidden" value="997454dc58799e806f18d21eac296581a8c6ef02" /> <input autocomplete="off" id="id_captcha_1" name="captcha_1" type="text" />#}
                    </div>
                    <div>
                      {% for err in forgetForm.errors.items %}{{ err }}{% endfor %}{{ msg }}
                    </div>
                    <input type="hidden" name="sms_type" value="1"/>
                    <input class="btn btn-green" id="jsFindPwdBtn" type="submit" value="提交" />
                    <p class="form-p" style="bottom:40px;">您还可以<a href="login.html"> [直接登录]</a></p>
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/validateDialog.js"  type="text/javascript"></script>
<script src="/static/js/login.js"  type="text/javascript"></script>
</body>
</html>

templates/org-list.html
{% extends 'base.html' %}
{% block title %}
    课程机构列表 - 慕学在线网
{% endblock %}

{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="index.html">首页</a>></li>
            <li>课程机构</li>
        </ul>
    </div>
</section>
{% endblock %}

{% block nav %}
<nav>
    <div class="nav">
        <div class="wp">
            <ul>
                <li ><a href="index.html">首页</a></li>
                <li>
                    <a href="{% url 'org:courseList' %}">
                        公开课<img class="hot" src="/static/images/nav_hot.png">
                    </a>
                </li>
                <li >
                    <a href="{% url 'org:teacherList' %}">授课教师</a>
                </li>
                <li class="active"><a href="{% url 'org:orgList' %}">授课机构</a></li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<section>
	<div class="wp butler_list_box list">
	<div class='left'>
		<div class="listoptions">
			<ul>
				<li>
					<h2>机构类别</h2>
					<div class="cont">
                        <a href="?city="><span class="{% if category == '' %}active2{% endif %}">全部</span></a>

                            <a href="?category=pxjg&city={{ city_id }}"><span class="{% if category == 'pxjg' %}active2{% endif %}">培训机构</span></a>

                            <a href="?category=gx&city={{ city_id }}"><span class="{% if category == 'gx' %}active2{% endif %}">高校</span></a>

                            <a href="?category=gr&city={{ city_id }}"><span class="{% if category == 'gr' %}active2{% endif %}">个人</span></a>

					</div>
				</li>
				<li>
					<h2>所在地区</h2>
					<div class="more">更多</div>
					<div class="cont">
                        <a href="?ct="><span class="{% ifequal city_id '' %}active2{% endifequal %}">全部</span></a>
                        {% for city in all_citys %}
                            <a href="?city={{ city.id }}"><span class="{% ifequal city.id|stringformat:"i" city_id %}active2{% endifequal %}">{{ city.name }}</span></a>
                        {% endfor %}
					</div>
				</li>
			</ul>
		</div>
		<div class="all">共<span class="key">{{ org_nums }}</span>家</div>
		<div class="butler_list company list">
		<div class="layout">
			<div class="head">
				<ul class="tab_header">
					<li class="{% ifequal sort '' %}active{% endifequal%}"><a href="?ct=&city=">全部</a> </li>
					<li class="{% ifequal sort 'students' %}active{% endifequal %}"><a href="?sort=students&category={{ category }}&city={{ city_id }}">学习人数 &#8595;</a></li>
					<li class="{% ifequal sort 'courses' %}active{% endifequal %}"><a href="?sort=courses&category={{ category }}&city={{ city_id }}">课程数 &#8595;</a></li>
				</ul>
			</div>

            {% for org in all_orgs.object_list %}
                <dl class="des difdes">
                    <dt>
                        <a href="{% url 'org:org_detail' org.id %}">
                            <img width="200" height="120" class="scrollLoading" data-url="{{ MEDIA_URL }}{{ org.image }}"/>
                        </a>
                    </dt>
                    <dd>
                        <div class="clearfix">
                             <a href="{% url 'org:org_detail' org.id %}">
                                 <h1>{{ org.name }}</h1>
                                 <div class="pic fl">
                                         <img src="/static/images/authentication.png"/>
                                         <img src="/static/images/gold.png"/>
                                 </div>
                             </a>
                        </div>
                        <ul class="cont">
                            <li class="first"><p class="pic9">课程数：<span>{{ org.class_nums }}</span></p><p class="c7">学习人数：<span>{{ org.student_nums }}</span></p></li>
                            <li class="c8" style="padding-left:18px;">{{ org.address }}</li>
                            <li class="pic10" style="padding-left:18px;">经典课程：

                                    <a href="/diary/19/">c语言基础入门</a>

                                    <a href="/diary/16/">数据库基础</a>

                            </li>
                        </ul>
                    </dd>
                    <div class="buy start_groupbuy jsShowPerfect2" data-id="22"><br/>联系<br/>服务</div>
                </dl>
            {% endfor %}
		</div>
		 <div class="pageturn">
            <ul class="pagelist">
                {% if all_orgs.has_previous %}
                    <a href="?{{ all_orgs.previous_page_number.querystring }}" class="long">上一页</a>
                {% endif %}
                {% for page in all_orgs.pages %}
                    {% if page %}
                        {% ifequal page all_orgs.number %}
                            <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                        {% else %}
                            <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                        {% endifequal %}
                    {% else %}
                        <li class="none"><a href="">...</a></li>
                    {% endif %}
                {% endfor %}
                {% if all_orgs.has_next %}
                     <li class="long"><a href="?{{ all_orgs.next_page_number.querystring }}">下一页</a></li>
                {% endif %}
            </ul>
        </div>
		</div>
	</div>
	<div class="right companyright">
			<div class="head">我要学习</div>
			<form class="rightform" id="jsStayForm">
				<div>
                    <img src="/static/images/rightform1.png"/>
                    <input type="text" name="name" id="companyName" placeholder="名字" maxlength="25" />
                </div>
				<div>
                    <img src="/static/images/rightform2.png"/>
                    <input type="text" name="mobile" id="companyMobile" placeholder="联系电话"/>
                </div>
				<div>
                    <img src="/static/images/rightform3.png"/>
                    <input type="text" name="course_name" id="companyAddress" placeholder="课程名" maxlength="50" />
                </div>
                <p class="error company-tips" id="jsCompanyTips"></p>
				<input class="btn" type="text" id="jsStayBtn" value="立即咨询 >" />
                {% csrf_token %}
            </form>
		</div>

		<div class="right companyrank layout">
			<div class="head">授课机构排名</div>
                {% for org in institution_ranking %}
                    <dl class="des">
                        <dt class="num fl">{{ forloop.counter }}</dt>
                        <dd>
                            <a href="/company/2/"><h1>{{ org.name }}</h1></a>
                            <p>{{ org.address }}</p>
                        </dd>
                    </dl>
                {% endfor %}
		    </div>
        </div>
</section>
{% endblock %}

{% block custom_js %}
<script>
    $(function(){
        $('#jsStayBtn').on('click', function(){
            $.ajax({
                cache: false,
                type: "POST",
                url:"{% url 'org:addAsk' %}",
                data:$('#jsStayForm').serialize(),
                async: true,
                success: function(data) {
                    if(data.status == 'success'){
                        $('#jsStayForm')[0].reset();
                        alert("提交成功")
                    }else if(data.status == 'fail'){
                        $('#jsCompanyTips').html(data.msg)
                    }
                },
            });
        });
    })

</script>
{% endblock %}

</body>
</html>

templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="/reset_password/" method="post">
        {% csrf_token %}
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li class="button">
                    <div class="error btns" id="jsForgetTips">
                      {% for err in forgetForm.errors.items %}{{ err }}{% endfor %}{{ msg }}
                    </div>
                    <input type="hidden" name='user_email' value='{{ user_email }}' />
                    <input class="btn btn-green" id="jsFindPwdBtn" type="submit" value="提交" />
{#                    <input type="submit" value="提交" >#}
                </li>
            </ul>
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="/static/images/check2.png">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>慕学在线注册</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">

</head>
<body>
<div class="loginbox dialogbox">
    <h1>账号登录</h1>
    <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
    <div class="cont">
        <form id="jsLoginForm" autocomplete="off">
            <div class="box">
                <span class="word3">用户名</span>
                <input type="text" name="account_l" id="account_l" placeholder="手机号/邮箱" />
            </div>
            <div class="box">
                <span class="word2">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</span>
                <input type="password" name="password_l" id="password_l" placeholder="请输入您的密码"/>
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips"></div> <!--登录错误提示-->
            <div class="btns">
                <span><input type="checkbox" id="jsAutoLogin" />&nbsp;自动登录</span>
                <span class="forget btn fr">忘记密码</span>
            </div>
            <div class="button">
                <input type="button" value="登录" id="jsLoginBtn" />
            </div>
            <div class="btns">
                <span class="fr">没有账号？<span class="regist btn">立即注册</span></span>
            </div>
        </form>
    </div>
</div>
<div class="dialog" id="jsDialog">
    <!--提示弹出框-->
    <div class="successbox dialogbox" id="jsSuccessTips">
        <h1>成功提交</h1>
        <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
        <div class="cont">
            <h2>您的需求提交成功！</h2>
            <p></p>
        </div>
    </div>
    <div  class="noactivebox dialogbox" id="jsUnactiveForm" >
        <h1>邮件验证提示</h1>
        <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
        <div class="center">
            <img src="/static/images/send.png"/>
            <p>我们已经向您的邮箱<span class="green" id="jsEmailToActive">12@13.com</span>发送了邮件，<br/>为保证您的账号安全，请及时验证邮箱</p>
            <p class="a"><a class="btn" id="jsGoToEmail" target="_blank" href="http://mail.qq.com">去邮箱验证</a></p>
            <p class="zy_success upmove"></p>
            <p style="display: none;" class="sendE2">没收到，您可以查看您的垃圾邮件和被过滤邮件，也可以再次发送验证邮件（<span class="c5c">60s</span>）</p>
            <p class="sendE">没收到，您可以查看您的垃圾邮件和被过滤邮件，<br/>也可以<span class="c5c green" id="jsSenEmailAgin" style="cursor: pointer;">再次发送验证邮件</span></p>
        </div>
    </div>
</div>

<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">慕学在线，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>4001008031</span></li>
                <li><a href="/login/">[登录]</a></li>
                <li class="active"><a href="/register/">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="/index/"></a>
                <h1>用户注册</h1>
                <a class="index-font" href="/index/">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">

                        <li><a href=""><img width="483" height="472" src="/static/images/57a801860001c34b12000460.jpg" /></a></li>

                        <li><a href=""><img width="483" height="472" src="/static/images/57a801860001c34b12000460.jpg" /></a></li>

                        <li><a href=""><img width="483" height="472" src="/static/images/57a801860001c34b12000460.jpg" /></a></li>

                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <div class="tab">
                    <!--<h2 class="active">手机注册</h2>-->
                    <h2>邮箱注册</h2>
                </div>
                <!--<div class="tab-form">-->
                    <!--<form id="mobile_register_form" autocomplete="off">-->
                        <!--<input type='hidden' name='csrfmiddlewaretoken' value='gTZljXgnpvxn0fKZ1XkWrM1PrCGSjiCZ' />-->
                        <!--<div class="form-group marb20">-->
                            <!--<label>手&nbsp;机&nbsp;号</label>-->
                            <!--<input id="jsRegMobile" name="account" type="text" placeholder="请输入您的手机号码" />-->
                        <!--</div>-->
                        <!--<div class="form-group marb20" id="jsRefreshCode">-->
                            <!--<label>验&nbsp;证&nbsp;码</label>-->
                            <!--<input autocomplete="off" class="form-control-captcha mobile-register-captcha" id="mobile-register-captcha_1" name="captcha_m_1" placeholder="请输入验证码" type="text" /> <input class="form-control-captcha mobile-register-captcha" id="mobile-register-captcha_0" name="captcha_m_0" placeholder="请输入验证码" type="hidden" value="29953bacf7005e8469388b449d97d00d523c1706" /> &nbsp;<img src="/captcha/image/29953bacf7005e8469388b449d97d00d523c1706/" alt="captcha" class="captcha" />-->
                        <!--</div>-->
                        <!--<div class="clearfix">-->
                            <!--<div class="form-group marb8 verify-code">-->
                                <!--<label>短信验证码</label>-->
                                <!--<input id="jsPhoneRegCaptcha" name="mobile_code" type="text" placeholder="输入手机验证码" />-->
                            <!--</div>-->
                            <!--<input class="verify-code-btn sendcode" id="jsSendCode" value="发送验证码">-->
                        <!--</div>-->
                        <!--<div class="form-group marb8">-->
                            <!--<label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>-->
                            <!--<input id="jsPhoneRegPwd" name="password_m" type="password" placeholder="请输入6-20位非中文字符密码" />-->
                        <!--</div>-->
                        <!--<div class="error btns" id="jsMobileTips"></div>-->
                        <!--<div class="auto-box marb8">-->

                        <!--</div>-->
                        <!--<input class="btn btn-green" id="jsMobileRegBtn" type="button" value="注册并登录" />-->
                    <!--</form>-->
                <!--</div>-->
                <div class="tab-form">
                    <form id="email_register_form" method="post" action="/register/" autocomplete="off">
                        <div class="form-group marb20 {% if register_form.errors.email %}errorput{% endif %}">
                            <label>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</label>
                            <input  type="text" id="id_email" name="email" value="{{ register_form.email.value }}" placeholder="请输入您的邮箱地址" />
                        </div>
                        <div class="form-group marb8 {% if register_form.errors.password %}errorput{% endif %} ">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password"  value="{{ register_form.password.value }}" placeholder="请输入6-20位非中文字符密码" />
                        </div>
                        <div class="form-group marb8 captcha1 {% if register_form.errors.captcha %}errorput{% endif %}">
                            <label>验&nbsp;证&nbsp;码</label>
                            {{ register_form.captcha }}
{#                            <img src="/captcha/image/2f3f82e5f7a054bf5caa93b9b0bb6cc308fb7011/" alt="captcha" class="captcha" /> <input id="id_captcha_0" name="captcha_0" type="hidden" value="2f3f82e5f7a054bf5caa93b9b0bb6cc308fb7011" /> <input autocomplete="off" id="id_captcha_1" name="captcha_1" type="text" />#}
                        </div>

                             <div class="error btns" id="jsEmailTips"> {% for key,err in register_form.errors.items %} {{ err }} {% endfor %}{{ msg }}</div>

{#                            {%  if msg %}#}
{#                                <div class="error btns" id="send_email">点击重发邮件</div>#}
{#                                <input type="hidden" value="{{ user_id }}" id="user_id">#}
{#                            {% endif %}#}

{#                        <div class="error btns" >#}
{#                            {% if msg %}#}
{#                                <input class="error btns" type="button" value="点击重发邮件" >#}
{#                                <input type="hidden" value="{{ user_id }}" id="user_id">#}
{#                            {% endif %}#}
{#                        </div>#}
                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录" />
                        {% csrf_token %}
                    </form>
                </div>
                <p class="form-p">已有账号？<a href="/login/">[立即登录]</a></p>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/validateDialog.js"  type="text/javascript"></script>
<script src="/static/js/login.js"  type="text/javascript"></script>
{#<script>#}
{#    $(document).ready(function(){#}
{#        $("#send_email").click(function(){#}
{#            var u_id = $('#user_id').val();#}
{##}
{#            $.get('/resend_email/',{'id':u_id}, function (ret) {#}
{#                alert(ret['status'])#}
{#            })#}
{#        })#}
{#    })#}
{#</script>#}
</body>
</html>